update
upgrade

tap homebrew/versions
tap homebrew/binary
tap sanemat/font
tap codekitchen/dinghy

install mysql
install imagemagick
install pkg-config

install homebrew/X11/xquartz

install redis
install phantomjs
install heroku-toolbelt
install cmake
install hub
install vifm
install vim --with-lua
install zsh
install ricty
install fortune
install nodebrew
install hub
install pyenv
install fortune
install jq
install peco

cask install google-chrome
cask install skype
cask install slack
cask install dashlane
cask install pandoc
cask install item2
cask install peco

cask install virtualbox
cask install vagrant
install dinghy
install docker docker-machine
cask install minikube
install docker-machine-driver-xhyve

cask install blender
