update
upgrade

tap homebrew/versions
tap homebrew/binary

install mysql
install imagemagick

install docker boot2docker
cask install virtualbox

install redis
install phantomjs
install heroku-toolbelt
install cmake
install hub
install vifm
install macvim --with-lua

cask install skype
cask install hipchat

